# Generated by Django 4.2.16 on 2024-11-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movieinfo_genres_alter_movieinfo_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userspage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('favorite_movies', models.ManyToManyField(blank=True, related_name='favorated_by', to='app.movieinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='watchlisted_by', to='app.movieinfo')),
            ],
        ),
    ]
