# Generated by Django 4.2.16 on 2024-11-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspage', '0006_review_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
    ]
