# Generated by Django 4.2.16 on 2024-11-09 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspage', '0007_remove_userprofile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userImage',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
