# Generated by Django 4.2.16 on 2024-11-09 09:29

import django.core.validators
from django.db import migrations, models
import userspage.models


class Migration(migrations.Migration):

    dependencies = [
        ('userspage', '0008_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.FileField(blank=True, null=True, upload_to=userspage.models.user_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
