# Generated by Django 4.2.16 on 2024-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='genres',
            field=models.ManyToManyField(to='app.genres'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movieReleaseDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='trailerUrl',
            field=models.URLField(),
        ),
    ]
