# Generated by Django 4.2.16 on 2024-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movieinfo_genres_alter_movieinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.FileField(upload_to='static/uploads'),
        ),
    ]
