# Generated by Django 4.2.16 on 2024-11-07 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movieinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.FileField(upload_to='static/uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
