# Generated by Django 4.2.16 on 2024-12-04 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movieinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
