# Generated by Django 4.2.16 on 2024-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movieinfo_rating_movieinfo_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
